### PR TITLE
Add support for system-playlist kind so that "discover" playlists are loaded

### PR DESCRIPTION
**Pull request by alistairmaclean**
Some playlists aren't resolved as their kind is "system-playlist" rather than the expected value of "playlist", but both seem to behave the same for my use-case (fetching track stream urls).

A system-playlist to test and reproduce with:
https://soundcloud.com/discover/sets/your-playback::alexabx:2022

Here's a quick fix, let me know if and how you would like tests implemented.

### CODE REVIEW

**Review by thedtvn — APPROVED** [review]
is good

**Comment by 3jackdaws** [comment]
@alistairmaclean Just a simple test that resolves that playlist without errors and maybe checks that some properties are there would be enough.

**Comment by alistairmaclean** [comment]
@3jackdaws - pushed some tests.

I changed the `Playlist.__len__` logic since `track_count` and the following attributes are missing from the Soundcloud API when resolving system-playlists (maybe this justifies defining a separate system playlist python object):
```
{'display_date', 'reposts_count', 'set_type', 'release_date', 'label_name', 'duration', 'ready', 'managed_by_feeds', 'public', 'secret_token', 'is_album', 'embeddable_by', 'created_at', 'license', 'purchase_url', 'client', 'last_modified', 'genre', 'purchase_title', 'uri', 'track_count', 'user_id', 'sharing', 'tag_list', 'published_at'}
```

With this in mind, the `test_playlist_size` tests are redundant so I have removed them.

Let me know your thoughts, I'm happy to amend as required. 

Thanks.

**Review by 3jackdaws — APPROVED** [review]

**Comment by 3jackdaws** [comment]
Hey @alistairmaclean , can you pull from master to update the github workflow pythonapp.yml so that it looks kinda like this:
```
name: Build & Test

on: [push, pull_request, workflow_dispatch]
```

and the build and test workflow can run?

Once the tests run successfully, I'll merge.

**Comment by alistairmaclean** [comment]
Thanks.

Do you have a release date in mind?

**Comment by 3jackdaws** [comment]
0.6.1 should be live now

**Pull request merged**
