### PR TITLE
Bugfix/find script url

### LINKED ISSUE #6: find_client_id is failing
```
File "sclib\sync.py", line 48, in get_credentials

self.client_id = util.find_client_id(script_text)

File "sclib\util.py", line 23, in find_client_id

return re.findall(r'client_id:"([a-zA-Z0-9]+)"', script_text)[0]
IndexError: list index out of range
```

Obviously "script_text" isn't getting the proper response. I'll continue debugging if this project is alive.

### PR DESCRIPTION
**Pull request by alistairmaclean**
Fixes 3jackdaws/soundcloud-lib#6

Forgive any misdoing on my behalf, it's my first Github PR.

I'm happy to oblige and amend commits to fit standards expected by the author.

Thanks.

### CODE REVIEW

**Comment by alistairmaclean** [comment]
@3jackdaws Is this of any interest?

**Comment by 3jackdaws** [comment]
Thanks for your contribution! I will merge this as soon as I can pull it and run tests.

**Review by 3jackdaws — APPROVED** [review]
The "48-" js file is the one where the client id can be found.  I'll approve this because it is an improvement, but the tests still don't pass.

**Comment by alistairmaclean** [comment]
Apologies, I had just assumed tests were unaffected. It appears there are two areas of concern;

**Fetching tracks by track ids**  
~~When fetching a batch of tracks by track ids, SoundCloud is returning 401 Unauthorized when using the `ids` querystring on the `/tracks` resource endpoint. I assume they are trying to crack down our sort of use-case.~~

~~What your thoughts on mitigating this with concurrency, requesting every individual track?~~
~~It's far from ideal, a lot more network overhead, and a lot more requests towards rate limiting.~~

~~Docs state rate limiting is against the client_id, so we could fetch a new one when rate limited.~~

After further investigation, Soundcloud has simply limited the request to 50 ids. So, some concurrency is probably required.

**HLS assembly**  
What's your thoughts on implementing a library to do this? I came across https://github.com/Eyevinn/hls-download

Let me know and thanks again.

**Comment by alistairmaclean** [comment]
Closed this to open a new PR with further improvements under a 1.5.1 release version.

**Pull request closed without merging**
