### PR TITLE
support for on.soundcloud links

### LINKED ISSUE #44: no support for 'https://on.soundcloud.com' type links
on soundcloud mobile you can share a track or playlist, tapping copy link will generate a link with some metadata in it
e.g. https://soundcloud.com/shift-key/on-my-mind -> https://on.soundcloud.com/QnSJh

when you navigate to one of these links it will send a http 302 with the full soundcloud url in the location header.
currently passing one of these links to resolve raises a 404 error which I didn't expect

```python
from sclib import SoundcloudAPI, Track

api = SoundcloudAPI()
track = api.resolve('https://on.soundcloud.com/QnSJh')

assert type(track) is Track

filename = f'./{track.artist} - {track.title}.mp3'
print(filename)
```

returns an error

```
<class 'urllib.error.HTTPError'> HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/user\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/user\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "/user\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "/user\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/user\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/user\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "example.py", line 4, in <module>
    track = api.resolve('https://on.soundcloud.com/QnSJh')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Downloads\pythontemp\.venv\Lib\site-packages\sclib\sync.py", line 84, in resolve
    if obj['kind'] == 'track':
       ~~~^^^^^^^^
TypeError: 'bool' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by degendemolisher**
fixes #44 
in resolve(),
get redirect link (soundcloud.com) if regex detects anything other than that (e.g. on.soundcloud.com)
regex here https://regex101.com/r/jK3gNT/1

### CODE REVIEW

**Review by Aden720 — APPROVED** [review]
tested the sync method with these changes, and is returning the expected results. this seems like a fine solution.

**Comment by 3jackdaws** [comment]
@degendemolisher can you fix the linting errors called out in [the autolinter run](https://github.com/3jackdaws/soundcloud-lib/actions/runs/11419148620/job/32760703372?pr=45)? 

You can run linting locally by doing `make lint` on the command line

**Comment by degendemolisher** [comment]
Should I add requests in requirements_dev.txt?

**Comment by 3jackdaws** [comment]
It would be nice to avoid adding more dependencies.  Can you redo the part that requires `requests` to use `urllib`?

**Comment by 3jackdaws** [comment]
There's `get_obj_from` and `get_url` utility functions in `util.py`

**Comment by degendemolisher** [comment]
one of the testing track id is invalid iirc, I changed it to something else and the test worked

**Comment by 3jackdaws** [comment]
Cool, if you push up the changed test and it passes, I'll approve

**Review by 3jackdaws — APPROVED** [review]

**Pull request merged**
